server:
  port: 8800
  servlet:
    context-path: /client-tools
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
  mapper-locations: classpath:com/hltn/test/mapper/xml/*.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/client_tools?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 990729
